name: Docker Image

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag arces/swamp-api:$(date +%s)
    - name: Save image
      run: docker save -o ./swampPack.docker arces/swamp-api:$(date +%s)
